global using System;
global using RWCustom;
global using UnityEngine;
global using Debug = UnityEngine.Debug;
global using System.Runtime.CompilerServices;
global using BepInEx;
global using System.Security.Permissions;
global using BepInEx.Logging;
global using MonoMod.RuntimeDetour;
global using System.Reflection;